server:
  port: 8080

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: TmV3U2VjcmV0S2V5Rm9yQXJjaGl2YWxTZXJ2aWNlSldUU2lnbmluZ1B1cnBvc2U
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework: DEBUG
    com.healthcare: DEBUG
